using Script.CoreUObject;

namespace Script.CoreUObject
{
	[PathName("/Script/CoreUObject.EUnit")]
	public enum EUnit : byte
	{
		Micrometers = 0,
		Millimeters = 1,
		Centimeters = 2,
		Meters = 3,
		Kilometers = 4,
		Inches = 5,
		Feet = 6,
		Yards = 7,
		Miles = 8,
		Lightyears = 9,
		Degrees = 10,
		Radians = 11,
		CentimetersPerSecond = 12,
		MetersPerSecond = 13,
		KilometersPerHour = 14,
		MilesPerHour = 15,
		Celsius = 16,
		Farenheit = 17,
		Kelvin = 18,
		Micrograms = 19,
		Milligrams = 20,
		Grams = 21,
		Kilograms = 22,
		MetricTons = 23,
		Ounces = 24,
		Pounds = 25,
		Stones = 26,
		Newtons = 27,
		PoundsForce = 28,
		KilogramsForce = 29,
		KilogramCentimetersPerSecondSquared = 30,
		NewtonMeters = 31,
		KilogramCentimetersSquaredPerSecondSquared = 32,
		Hertz = 33,
		Kilohertz = 34,
		Megahertz = 35,
		Gigahertz = 36,
		RevolutionsPerMinute = 37,
		Bytes = 38,
		Kilobytes = 39,
		Megabytes = 40,
		Gigabytes = 41,
		Terabytes = 42,
		Lumens = 43,
		Milliseconds = 50,
		Seconds = 51,
		Minutes = 52,
		Hours = 53,
		Days = 54,
		Months = 55,
		Years = 56,
		Multiplier = 59,
		Percentage = 58,
		Unspecified = 64,
	}
}