using Script.CoreUObject;

namespace Script.ModelingToolsEditorMode
{
	[PathName("/Script/ModelingToolsEditorMode.EModelingModeAssetGenerationLocation")]
	public enum EModelingModeAssetGenerationLocation : int
	{
		AutoGeneratedWorldRelativeAssetPath = 0,
		AutoGeneratedGlobalAssetPath = 1,
		CurrentAssetBrowserPathIfAvailable = 2,
	}
}